BeFit_Website/BeFit_Website/Pages/FoodInfo/SearchForFood.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.Text;

namespace BeFit_Website.Pages.FoodInfo
{
    public class SearchForFoodModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();

        public Food food { get; set; } = new();
        public string ErrorMessage { get; set; } = string.Empty;

        public CombineFood_SelectedFood Food_SelectedFood { get; set; } = new();
        public SelectedFood SelectedFood { get; set; }
        public List<SpecialFood> SpecialFood { get; set; } = new();
        public async Task OnGet(Food? searchedFood, string? errorMessage)
        {
            food = searchedFood;
            ErrorMessage = errorMessage;

        }


        public async Task<IActionResult> OnPostSearch(Food food)
        {

            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);

            var request = await client.GetAsync($"/api/get-food{food.name}");
            if (request.IsSuccessStatusCode)
            {
                var stringData = request.Content.ReadAsStringAsync().Result;
                food = JsonConvert.DeserializeObject<Food>(stringData);
                HttpContext.Session.SetString("SearchedFood", stringData);
                return RedirectToPage("", food);
            }
            else
            {
                string error = request.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                return RedirectToPage("", new { errorMessage = error });
            }
            return new NoContentResult();
        }
        public async Task<IActionResult> OnPostAddFood(CombineFood_SelectedFood Food_SelectedFood)
        {

            var currentUser = HttpContext.Session.GetString("Id");

            Food_SelectedFood.CombinedSelectedFood.UserId = Guid.Parse(currentUser.ToString().Replace("\"", ""));
            //calling the searched food to pop up
            var stringData = HttpContext.Session.GetString("SearchedFood");
            var searchedFood = JsonConvert.DeserializeObject<Food>(stringData);
            Food_SelectedFood.CombinedFood = searchedFood;

            //continue calling api
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var jsoncategory = JsonConvert.SerializeObject(Food_SelectedFood);
            var content = new StringContent(jsoncategory, Encoding.UTF8, "application/json");
            var request = await client.PostAsync("api/add-selected-food", content);

            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }

            return new NoContentResult();

        }
    }
}

BeFit_Website/BeFit_Website/Pages/FoodInfo/SpecialFood.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text;

namespace BeFit_Website.Pages.FoodInfo
{
    public class SpecialFoodModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();

        public List<SpecialFood> specialFoodList { get; set; } = new();

        public SpecialFood specialFood { get; set; } = new();
        public CombineSpecialFood_SelectedFood SpecialFood_SelectedFood { get; set; } = new();
        public async Task OnGet()
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetStringAsync("api/get-special-food/" + currentUser.ToString().Replace("\"", ""));

            if (request != null)
            {
                //var stringData = request.Content.ReadAsStringAsync().Result();
                specialFoodList = JsonConvert.DeserializeObject<List<SpecialFood>>(request);
            }
        }
        public async Task<IActionResult> OnPostAddSpecialFood(SpecialFood specialFood)
        {
            var currentUser = HttpContext.Session.GetString("Id");
            specialFood.UserId = Guid.Parse(currentUser.ToString().Replace("\"", ""));
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var jsoncategory = JsonConvert.SerializeObject(specialFood);
            var content = new StringContent(jsoncategory, Encoding.UTF8, "application/json");
            var request = await client.PostAsync("/api/add-special-food", content);
            if (request.IsSuccessStatusCode)
            {

                return RedirectToPage("");
            }
            //else
            //{
            //    string error = request.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            //    return RedirectToPage("", new { errorMessage = error });
            //}
            return new NoContentResult();
        }
        public async Task<IActionResult> OnPostSelect(Guid itemid,CombineSpecialFood_SelectedFood SpecialFood_SelectedFood)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/get-one-special-food/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                var stringData = request.Content.ReadAsStringAsync().Result;
                HttpContext.Session.SetString("SelectedSpecialFood", stringData);
                var selectedSpecialFood = JsonConvert.DeserializeObject<SpecialFood>(stringData);
                var currentUser = HttpContext.Session.GetString("Id");

                SpecialFood_SelectedFood.CombinedSelectedFood.UserId = Guid.Parse(currentUser.ToString().Replace("\"", ""));


                SpecialFood_SelectedFood.CombinedSpecialFood = selectedSpecialFood;

                 httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
                 client = httpClient.CreateClient();
                client.BaseAddress = new Uri(config["BaseAddress"]);
                var jsoncategory = JsonConvert.SerializeObject(SpecialFood_SelectedFood);
                var content = new StringContent(jsoncategory, Encoding.UTF8, "application/json");
                 request = await client.PostAsync("api/add-special-food-to-selected-food", content);

                if (request.IsSuccessStatusCode)
                {
                    return RedirectToPage("");
                }
            }
            return new NoContentResult();
        }
        public async Task<IActionResult> OnPostDeleteSpecialFood(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/delete-special-food/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }

    }
}

BeFit_Website/BeFit_Website/Pages/FoodInfo/SearchForFood.cshtml
@page
@model BeFit_Website.Pages.FoodInfo.SearchForFoodModel
@{

    <link href="~/css/searchforfood.css" rel="stylesheet"/>
    

    <div class="main">
        <div class="jumbotron" id="jumbotron">
            <h1 class="display-4 head" id="display">Here you will find the details of food you ate!</h1>
            <h4>All info is after the food has been cooked.</h4>
            <form method="post" class="form-inline" enctype="multipart/form-data">
                <input asp-for="food.name" class="foorm2" type="search" placeholder="Search" aria-label="Search" required>
                <button asp-page-handler="Search" class="btn btn-primary" id="searchBtn" type="submit">Search</button>
            </form>
        </div>
        <hr class="my-3">
        <h1>Let us share with you your meals!</h1>
        <h2>Here it is:</h2>
        @if (!string.IsNullOrEmpty(Model.food.name))
        {
            <div class="mtable">
                <table class="rtable">
                    <thead>
                        <tr>
                            <th style="font-weight: bold;">Name</th>
                            <th>@Model.food.name</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="font-weight: bold;">Calories</td>
                            <td>@Model.food.calories</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Total Fats(g)</td>
                            <td>@Model.food.fat_total_g</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Saturated Fats(g)</td>
                            <td>@Model.food.fat_saturated_g</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Protien(g)</td>
                            <td>@Model.food.protein_g</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Sodium (mg)</td>
                            <td>@Model.food.sodium_mg</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Pottassium(mg)</td>
                            <td>@Model.food.potassium_mg</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Cholestrol(mg)</td>
                            <td>@Model.food.cholesterol_mg</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Carbs(g)</td>
                            <td>@Model.food.carbohydrates_total_g</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Fiber(g)</td>
                            <td>@Model.food.fiber_g</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold;">Sugar(g)</td>
                            <td>@Model.food.sugar_g</td>
                        </tr>
                    </tbody>
                </table>
                <button type="button" class="btn" id="addBtn" data-toggle="modal" data-target="#exampleModalCenter">
                    Add
                </button>
            </div>
        }
        else if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div>
                <span>
                    There were no results for your search.
                    <br>
                    <b>Suggestions:</b>
                    <br>
                    1- Make sure all words are spelled correctly.
                    <br>
                    2- Search by ingredient.
                    <br>
                    3- Try more general keywords like 'apple'.
                </span>
            </div>
        }
        else
        {
            <div class="mtable">
                <table class="rtable">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Food Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Calories</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Total Fats(g)</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Saturated Fats(g)</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Protien(g)</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Sodium (mg)</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Pottassium(mg)</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Cholestrol(mg)</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Carbs(g)</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Fiber(g)</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Sugar(g)</td>
                            <td>0</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        }

        <div class="special">
            <h6>Or you can just add your special food from here..!</h6>
            <a asp-page="/FoodInfo/SpecialFood"> <button type="button" class="btn btn-dark btn-sm">Add special food</button></a>
        </div>


        <!-- Modal -->

        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Details of food that you ate!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        <div class="modal-body">
                            <div class="Quantity">
                                <label for="tentacles">Quantity:</label>
                                <input type="number" asp-for="Food_SelectedFood.CombinedSelectedFood.Quantity" value="1" step="1" required>
                            </div>
                            <span asp-validation-for="Food_SelectedFood.CombinedSelectedFood.Quantity" class="text-danger"></span>
                            <div class="Weight">
                                <label for="tentacles">Weight(g):</label>
                                <input type="number" asp-for="Food_SelectedFood.CombinedSelectedFood.Weight" value="100" required>
                            </div>
                            <span asp-validation-for="Food_SelectedFood.CombinedSelectedFood.Weight" class="text-danger"></span>
                            <div class="dropdown2">
                                <select asp-for="Food_SelectedFood.CombinedSelectedFood.Meal" required>
                                    <option value="" id="hover" selected="selected" hidden>Select Meal</option>
                                    <option value="Breakfast">Breakfast</option>
                                    <option value="Lunch">Lunch</option>
                                    <option value="Dinner">Dinner</option>
                                    <option value="Snacks">Snack</option>
                                </select>
                            </div>
                            <span asp-validation-for="Food_SelectedFood.CombinedSelectedFood.Meal" class="text-danger"></span>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                                <button type="submit" asp-page-handler="AddFood" id="SaveBtn" class="btn btn-primary">Save </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_NavBar" />
    }
}

BeFit_Website/BeFit_Website/Pages/FoodInfo/SpecialFood.cshtml
@page
@model BeFit_Website.Pages.FoodInfo.SpecialFoodModel
@{
    int counter = 0;
    <head>
        <link href="~/css/specialfood.css" rel="stylesheet" />
    </head>
    <div class="jumbotron" id="jumbotron">
    <h1 class="display-4" id="display">Here you will find the food you made!</h1>
    <h4 >Make sure that the food is cooked before Weighting it for accuracy.</h4> 

  </div>
    <hr class="my-3">
    <h1 style="color:#1a1a1a;">Let us get some details about the food that you ate!  <button type="button"  id="SaveBtn" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalCenter">
      Add special Food
    </button></h1>
    <div class="mtable">
        <table class="rtable">
        <thead>
          <tr>
            <th >Name</th>
            <th>Calories</th>
            <th>Fats(g)</th>
            <th>Carbs(g)</th>
            <th>Protien(g)</th>
            <th>Manage</th>
          </tr>
        </thead>
        <tbody>
        @foreach (var obj in Model.specialFoodList)
        {
          <tr>
            <td>@obj.Name</td>
            <td>@obj.Calories</td>
            <td>@obj.Fats</td>
            <td>@obj.Carbs</td>
            <td>@obj.Protein</td>       
            <td>
            <button type="button" class="btn btn-primary showPopUp" data-toggle="modal" data-target=@("#exampleModal"+@counter) data-whatever="" id="SaveBtn">Add</button>
            <form method="post" enctype="multipart/form-data" style="display:inline;">
                <button type="submit" asp-page-handler="DeleteSpecialFood" class="btn" style="background:#dc3545; color:#ffffff;" asp-route-itemid="@obj.Id">Delete</button>
            </form>
            </td>
          </tr>

                    <div class="modal fade hide pop" id=@("exampleModal"+@counter) tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Add</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form method="post" enctype="multipart/form-data">
                                    <div class="modal-body" id="modalCONT">

                                        <div class="Quantity">
                                            <label for="tentacles">Quantity:</label>
                                            <input type="number" asp-for="SpecialFood_SelectedFood.CombinedSelectedFood.Quantity" value="1" step="1" required>
                                        </div>
                                            <span asp-validation-for="SpecialFood_SelectedFood.CombinedSelectedFood.Quantity" class="text-danger"></span>
                                        <div class="Weight">
                                            <label for="tentacles">Weight(g):</label>
                                            <input type="number" asp-for="SpecialFood_SelectedFood.CombinedSelectedFood.Weight" value="100" required>
                                        </div>
                                            <span asp-validation-for="SpecialFood_SelectedFood.CombinedSelectedFood.Weight" class="text-danger"></span>
                                        <div class="Weight">
                                            <label for="tentacles">Meal:</label>
                                            <select asp-for="SpecialFood_SelectedFood.CombinedSelectedFood.Meal" required>
                                                <option value="" hidden>Select Meal</option>
                                                <option value="Breakfast">Breakfast</option>
                                                <option value="Lunch">Lunch</option>
                                                <option value="Dinner">Dinner</option>
                                                <option value="Snacks">Snacks</option>
                                            </select>
                                        </div>
                                            <span asp-validation-for="SpecialFood_SelectedFood.CombinedSelectedFood.Meal" class="text-danger"></span>

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                                        <button type="submit" id="SaveBtn" class="btn btn-primary" asp-page-handler="Select" asp-route-itemid="@obj.Id">Add</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
        counter++;
        }
        </tbody>
      </table>
      
    
    <p class="lead">
    
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Details</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              <form method="post" enctype="multipart/form-data">
                    <div class="modal-body" id="modalCONT">
                    
                        <div class="Name"> <label for="tentacles">Name:</label>
                            <input type="text"  asp-for="specialFood.Name"></div>
                            <span asp-validation-for="specialFood.Name" class="text-danger" style="color:#aa0909"></span>
                        <div class="calories"> <label for="tentacles">Calories:</label>
                           <input type="number"  asp-for="specialFood.Calories" value=""></div>
                           <span asp-validation-for="specialFood.Calories" class="text-danger" style="color:#aa0909"></span>
                        <div class="fats"><label for="tentacles">Fats(g):</label>
                            <input type="number"  asp-for="specialFood.Fats" value=""></div>
                            <span asp-validation-for="specialFood.Fats" class="text-danger" style="color:#aa0909"></span>
                        <div class="protein"> <label for="tentacles">Protein(g):</label>
                            <input type="number"  asp-for="specialFood.Protein" value=""></div>
                            <span asp-validation-for="specialFood.Protein" class="text-danger" style="color:#aa0909"></span>
                        <div class="carbs"><label for="tentacles">Carbs(g):</label>
                            <input type="number"  asp-for="specialFood.Carbs" value=""></div>
                            <span asp-validation-for="specialFood.Carbs" class="text-danger" style="color:#aa0909"></span>



                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                      <button type="submit" id="SaveBtn" class="btn btn-primary" asp-page-handler="AddSpecialFood">Save </button>
                    </div>
              </form>
              </div>
            </div>
          </div>
    </p>
        
        
        

        
           
  </div>

}

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_NavBar" />
    }
}