BeFit_Website/BeFit_Website/Pages/Admin/AdminHome.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BeFit_Website.Pages.Admin
{
    public class AdminHomeModel : PageModel
    {
        public void OnGet()
        {
            var currentAdmin = HttpContext.Session.GetString("Id");
        }
    }
}

BeFit_Website/BeFit_Website/Pages/Admin/DeleteFeedbacks.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BeFit_Website.Pages.Admin
{
    public class DeleteFeedbacksModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();
        public List<GetFeedback> feedbackList { get; set; } = new();
        public Feedback Feedback { get; set; } = new();
        public User user { get; set; } = new();
        public async Task OnGet()
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetStringAsync("api/get-feedbacks");

            if (request != null)
            {
                //var stringData = request.Content.ReadAsStringAsync().Result();
                feedbackList = JsonConvert.DeserializeObject<List<GetFeedback>>(request);
            }
            var request2 = await client.GetAsync("api/get-user-data/" + currentUser.ToString().Replace("\"", ""));

            if (request2.IsSuccessStatusCode)
            {
                var stringData = request2.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<User>(stringData);
            }
        }
            public async Task<IActionResult> OnPostDeleteFeedback(Guid itemid)
            {
                var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
                var client = httpClient.CreateClient();
                client.BaseAddress = new Uri(config["BaseAddress"]);
                var request = await client.GetAsync("/api/delete-feedback/" + itemid);
                if (request.IsSuccessStatusCode)
                {
                    return RedirectToPage("");
                }
                return new NoContentResult();
            }
    }
}

BeFit_Website/BeFit_Website/Pages/Admin/DeleteUsers.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BeFit_Website.Pages.Admin
{
    public class DeleteUsersModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();
        public List<User> usersList { get; set; } = new();
        public async Task OnGet()
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetStringAsync("api/get-users");

            if (request != null)
            {
                //var stringData = request.Content.ReadAsStringAsync().Result();
                usersList = JsonConvert.DeserializeObject<List<User>>(request);
            }
        }
        public async Task<IActionResult> OnPostDeleteUser(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/delete-user/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }
        public async Task<IActionResult> OnPostRestoreUser(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/restore-user/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }
    }
}

BeFit_Website/BeFit_Website/Pages/Admin/ManageFeedbacks.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BeFit_Website.Pages.Admin
{
    public class ManageFeedbacksModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
          .AddJsonFile("appsettings.json")
          .AddEnvironmentVariables()
          .Build();
        public List<GetFeedback> feedbackList { get; set; } = new();
        public Feedback Feedback { get; set; } = new();
        public User user { get; set; } = new();
        public async Task OnGet()
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetStringAsync("api/get-feedbacks-for-admin");

            if (request != null)
            {
                //var stringData = request.Content.ReadAsStringAsync().Result();
                feedbackList = JsonConvert.DeserializeObject<List<GetFeedback>>(request);
            }
            var request2 = await client.GetAsync("api/get-user-data/" + currentUser.ToString().Replace("\"", ""));

            if (request2.IsSuccessStatusCode)
            {
                var stringData = request2.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<User>(stringData);
            }
        }
        public async Task<IActionResult> OnPostDeleteFeedback(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/delete-feedback/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }
        public async Task<IActionResult> OnPostApproveFeedback(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/approve-feedback/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }
    }
}

BeFit_Website/BeFit_Website/Pages/Admin/ManageUsers.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BeFit_Website.Pages.Admin
{
    public class ManageUsersModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();
        public List<User> usersList { get; set; } = new();
        public async Task OnGet()
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetStringAsync("api/get-users");

            if (request != null)
            {
                //var stringData = request.Content.ReadAsStringAsync().Result();
                usersList = JsonConvert.DeserializeObject<List<User>>(request);
            }
        }
        public async Task<IActionResult> OnPostDeleteUser(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/delete-user/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }
        public async Task<IActionResult> OnPostRestoreUser(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/restore-user/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }
    }
}

BeFit_Website/BeFit_Website/Pages/Admin/AdminHome.cshtml
@page
@model BeFit_Website.Pages.Admin.AdminHomeModel
@{
    <div class="text-center">
        <a class="btn btn-outline-primary" asp-page="/Admin/ManageUsers">Manage Users</a>
    </div>
    <div class="text-center">
        <a class="btn btn-outline-primary" asp-page="/Admin/ManageFeedbacks">Manage Feedbacks</a>
    </div>
    <div class="text-center">
        <a class="btn btn-outline-primary" asp-page="/UserInfo/Login">Logout</a>
    </div>
}

BeFit_Website/BeFit_Website/Pages/Admin/DeleteFeedbacks.cshtml
@page
@model BeFit_Website.Pages.Admin.DeleteFeedbacksModel
@{
    <head>
        <style>
            .container {
                width: 500px;
                overflow: hidden;
                /*background: #fff;*/
                border-radius: 10px;
                box-shadow: 0 12px 28px rgba(0, 0, 0, 0.12);
                margin: auto;
            }

            .post header {
                font-size: 22px;
                font-weight: 600;
                text-align: center;
                padding: 17px 0;
                border-bottom: 1px solid #bfbfbf;
            }

            .post form {
                margin: 20px 25px;
            }

                .post form .content {
                    display: flex;
                    align-items: center;
                }

                    .post form .content img {
                        max-width: 52px;
                    }

                    .post form .content .details {
                        margin: -3px 0 0 12px;
                    }

            form :where(input, button) {
                width: 100%;
                outline: none;
                border: none;
            }

            form input {
                resize: none;
                font-size: 18px;
                margin-top: 5px;
                min-height: 100px;
            }

            .delete {
                width: 10%;
            }

            form button {
                height: 53px;
                color: #fff;
                font-size: 18px;
                font-weight: 500;
                cursor: pointer;
                color: #BCC0C4;
                border-radius: 7px;
                background: #e2e5e9;
                transition: all 0.3s ease;
            }

            form button {
                color: #fff;
                background: #4599FF;
            }

                form button:hover {
                    background: #1a81ff;
                }
        </style>
    </head>
    <body>
        @foreach (var obj in Model.feedbackList)
        {
            <div class="container">
                        <form method="post" class="align-content-center col-6 w-25" enctype="multipart/form-data">
                            <button class="delete" type="submit" asp-page-handler="DeleteFeedback" asp-route-itemid=@obj.Id>❌</button>
                        </form>
                <div class="wrapper">
                    <section class="post">
                        <form>
                            <div class="content">
                                <img src="@obj.FeedbackUser.ProfileUrl" style="border-radius: 50%">
                                <div class="details">
                                    <p>@obj.FeedbackUser.UserName</p>
                                    <p>@obj.TimeCreated</p>
                                </div>
                            </div>
                            <input asp-for="@obj.Message" readonly="true">
                        </form>
                </div>
            </div>

        }

    </body>
}

BeFit_Website/BeFit_Website/Pages/Admin/DeleteUsers.cshtml
@page
@model BeFit_Website.Pages.Admin.DeleteUsersModel
@{
    <head>
        <style>
                table {
                    font-family: arial, sans-serif;
                    border-collapse: collapse;
                    width: 70%;
                    position: center;
                    margin-left: 10%
                }

                td, th {
                    border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;
                }

                tr:nth-child(even) {
                    background-color: #dddddd;
                }
        </style>
    </head>
    <h1> Users</h1>
    <table class="table table-bordered table-striped" >
        <thead>
            <tr>
                <th>Username</th>
                <th>E-mail</th>
                <th>Profile Picture</th>
                <th>Is Active</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.usersList)
            {
                <tr>
                    <td>@obj.UserName</td>
                    <td>@obj.Email</td>
                    <td><img src="@obj.ProfileUrl" style="border: 2px solid black" width="100px" height="100px"></td>
                    <td>@obj.IsActive</td>
                    <td>
                    <form method="post">
                            <button type="submit" asp-page-handler="DeleteUser" asp-route-itemid=@obj.Id>Delete ❌</button>
                    </form>
                    </td>
                    <td>
                        <form method="post">
                            <button type="submit" asp-page-handler="RestoreUser" asp-route-itemid=@obj.Id>Restore ♻️</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

BeFit_Website/BeFit_Website/Pages/Admin/ManageFeedbacks.cshtml
@page
@model BeFit_Website.Pages.Admin.ManageFeedbacksModel
@{
    <link href="~/css/managefeedbacks.css" rel="stylesheet"/>
    <link href="~/css/navbar.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/photos/be-fit12.png" width="80" draggable="false" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link btn " asp-page="/Admin/ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn " asp-page="/Admin/ManageFeedbacks">Manage Feedbacks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn " asp-page="/UserInfo/Login">Log out</a>
                </li>
            </ul>
        </div>
    </nav>
    <div style="margin-bottom:140px;"></div>
    <h1 style="margin-bottom: 30px;"> Manage Feedbacks</h1>
        @foreach (var obj in Model.feedbackList)
        {
            if (obj.Approved == false){
            <div class="feedback-container" style="background:#fae685">
                <form method="post" class="feedback-form" enctype="multipart/form-data">
                    <button class="delete" type="submit" asp-page-handler="DeleteFeedback" asp-route-itemid=@obj.Id>&#10008;</button>
                </form>
                <form method="post" class="feedback-form" enctype="multipart/form-data">
                    <button class="restore" type="submit" asp-page-handler="ApproveFeedback" asp-route-itemid=@obj.Id>&#10003;</button>
                </form>
                <div class="feedback-wrapper">
                    <section class="feedback-post">
                        <form class="feedback-form">
                            <div class="feedback-content">
                                <br>
                                <img src="@obj.FeedbackUser.ProfileUrl" style="border-radius: 50%">
                                <div class="details">
                                    <p>@obj.FeedbackUser.UserName</p>
                                    <p>@obj.TimeCreated</p>
                                </div>
                            </div>
                            <input type="text" asp-for="@obj.Message" readonly="true" style="background:#fae685">
                        </form>
                </div>
            </div>
            } else {
            <div class="feedback-container">
                <form method="post" class="feedback-form" enctype="multipart/form-data">
                    <button class="delete" type="submit" asp-page-handler="DeleteFeedback" asp-route-itemid=@obj.Id>&#10008;</button>
                </form>
                <form method="post" class="feedback-form" enctype="multipart/form-data">
                    <button class="restore" type="submit" asp-page-handler="ApproveFeedback" asp-route-itemid=@obj.Id>&#10003;</button>
                </form>
                <div class="feedback-wrapper">
                        <section class="feedback-post">
                        <form class="feedback-form">
                            <div class="feedback-content">
                            <br>
                                <img src="@obj.FeedbackUser.ProfileUrl" style="border-radius: 50%">
                                <div class="details">
                                    <p>@obj.FeedbackUser.UserName</p>
                                    <p>@obj.TimeCreated</p>
                                </div>
                            </div>
                            <input type="text" asp-for="@obj.Message" readonly="true">
                        </form>
                </div>
            </div>
            }


        }
}
<script src="~/js/managefeedbacks.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="~/js/bootstrap.bundle.min.js"></script>

BeFit_Website/BeFit_Website/Pages/Admin/ManageUsers.cshtml
@page
@model BeFit_Website.Pages.Admin.ManageUsersModel
@{
    <link href="~/css/manageusers.css" rel="stylesheet" />
    <link href="~/css/navbar.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/photos/be-fit12.png" width="80" draggable="false" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link btn " asp-page="/Admin/ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn " asp-page="/Admin/ManageFeedbacks">Manage Feedbacks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn " asp-page="/UserInfo/Login">Log out</a>
                </li>
            </ul>
        </div>
    </nav>
    <div style="margin-bottom:80px;"></div>
    <div class="container-fluid mt-5">
          <div class="row">
            <div class="col-12">
              <div class="container-fluid mt-5" style="margin-top: 70px;">

              <h1>Manage Users</h1>
            </div>
          </div>
          <table>
            <thead>
              <tr>
                <th>UserName</th>
                <th>Email</th>
                <th>Profile Picture</th>
                <th>Is Active</th>
              </tr>
            </thead>
            <tbody>
              @foreach (var obj in Model.usersList)
              {
              <tr>
                <td class="username-cell">@obj.UserName</td>
                <td class="email-cell">@obj.Email</td>
                <td class="profile-picture-cell"><img class="userImg" src="@obj.ProfileUrl" alt="None"></td>
                <td>@obj.IsActive</td>
                <td>
                  <form method="post">
                  <button class="delete" type="submit" asp-page-handler="DeleteUser" asp-route-itemid=@obj.Id><i class="fas fa-trash"></i>Delete</button>
                  </form>
                </td>
                <td>
                  <form method="post">
                    <button class="restore" type="submit" asp-page-handler="RestoreUser" asp-route-itemid=@obj.Id><i class="fas fa-undo">Restore</i></button>
                  </form>
                </td>
              </tr>
            }
            </tbody>
          </table>
        </div>
    </div>
}