BeFit_Website/BeFit_Website/Pages/UserInfo/EditUserData.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mime;
using System.Text;
namespace BeFit_Website.Pages.UserInfo
{
    public class EditUserModel : PageModel
    {

        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();

        [TempData]
        public string Msg { get; set; } = String.Empty;
        [TempData]
        public string Status { get; set; } = String.Empty;
        public User user { get; set; } = new();
        public async Task OnGet()
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("api/get-user-data/" + currentUser.ToString().Replace("\"", ""));

            if (request.IsSuccessStatusCode)
            {
                var stringData = request.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<User>(stringData);
            }

        }
        public async Task<IActionResult> OnPostEditUser(User user)
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var jsoncategory = JsonConvert.SerializeObject(user);
            //var content = new StringContent(jsoncategory, Encoding.UTF8, "application/json");
            user.Id = Guid.Parse(currentUser.ToString().Replace("\"", ""));
            var formData = new MultipartFormDataContent();
            formData = await MappingContent(formData, user);
            var request = await client.PutAsync("/api/edit-user-data", formData);
            if (request.IsSuccessStatusCode) { 
                return RedirectToPage("/Main/Home");
            }
            Msg = "User Already Exists";
            Status = "error";
            RedirectToPage("");
            return Page();
        }
        private async Task<MultipartFormDataContent> MappingContent(MultipartFormDataContent multipartFormDataContent, User user)
        {
            multipartFormDataContent.Add(new StringContent(user.Id.ToString(), Encoding.UTF8, MediaTypeNames.Text.Plain), "Id");
            multipartFormDataContent.Add(new StringContent(user.UserName, Encoding.UTF8, MediaTypeNames.Text.Plain), "UserName");
            multipartFormDataContent.Add(new StringContent(user.Email, Encoding.UTF8, MediaTypeNames.Text.Plain), "Email");
            multipartFormDataContent.Add(new StringContent(user.Password, Encoding.UTF8, MediaTypeNames.Text.Plain), "Password");

            if (user.ProfilePhoto != null)
            {

                var fileContent = new StreamContent(user.ProfilePhoto.OpenReadStream());
                fileContent.Headers.ContentType = MediaTypeHeaderValue.Parse(user.ProfilePhoto.ContentType);
                multipartFormDataContent.Add(fileContent, "ProfilePhoto", user.ProfilePhoto.FileName);
            }
            return multipartFormDataContent;
        }
    }

}

BeFit_Website/BeFit_Website/Pages/UserInfo/EditUserMacros.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text;

namespace BeFit_Website.Pages.UserInfo
{
    public class EditUserMacrosModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();
        public UserMacros userMacros { get; set; } = new();
        public async Task OnGet()
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("api/get-user-Macros/" + currentUser.ToString().Replace("\"", ""));

            if (request.IsSuccessStatusCode)
            {
                var stringData = request.Content.ReadAsStringAsync().Result;
                userMacros = JsonConvert.DeserializeObject<UserMacros>(stringData);
            }

        }
        public async Task<IActionResult> OnPost(UserMacros userMacros, Guid id)
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var jsoncategory = JsonConvert.SerializeObject(userMacros);
            var content = new StringContent(jsoncategory, Encoding.UTF8, "application/json");
            var request = await client.PutAsync($"/api/edit-user-macros{currentUser.ToString().Replace("\"", "")}", content);
            if (request.IsSuccessStatusCode)
            {
                
            }
            return RedirectToPage("/Main/Home");
        }
    }
}

BeFit_Website/BeFit_Website/Pages/UserInfo/FollowUpMessage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BeFit_Website.Pages.UserInfo
{
    public class FollowUpMessageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BeFit_Website/BeFit_Website/Pages/UserInfo/Login.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BeFit_Website.Pages.UserInfo
{
    public class LoginModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
              .AddJsonFile("appsettings.json")
              .AddEnvironmentVariables()
              .Build();

        [TempData]
        public string Msg { get; set; } = String.Empty;
        [TempData]
        public string Status { get; set; } = String.Empty;
        public User user { get; set; } = new();
        public void OnGet()
        {
            
        }

        public async Task<IActionResult> OnPost(User user)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var jsoncategory = JsonConvert.SerializeObject(user);
            var content = new StringContent(jsoncategory, Encoding.UTF8, "application/json");
            var request = await client.PostAsync("/api/login-user", content);

            if (request.IsSuccessStatusCode)
            {

                string id = request.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                HttpContext.Session.SetString("Id", id);
                request = await client.PostAsync($"/api/check-role{id.ToString().Replace("\"", "")}", content);
                if(request.IsSuccessStatusCode) 
                {
                    return RedirectToPage("/Admin/ManageFeedbacks");
                }
                request = await client.PostAsync($"/api/check-last-update{id.ToString().Replace("\"", "")}", content);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("/Main/Home");
            }
            return RedirectToPage("/UserInfo/FollowUpMessage");


            }
            Msg = "Wrong username or password";
            Status = "error";
            RedirectToPage("");
            return Page();
        }

    }
}

BeFit_Website/BeFit_Website/Pages/UserInfo/SignUp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text;
using BeFit_Website.DTO;
using System.Net.Mime;
using System.Net.Http.Headers;

namespace BeFit_Website.Pages.UserInfo
{
    public class SignUpModel : PageModel
    {
            IConfiguration config = new ConfigurationBuilder()
               .AddJsonFile("appsettings.json")
               .AddEnvironmentVariables()
               .Build();

        [TempData]
        public string Msg { get; set; } = String.Empty;
        [TempData]
        public string Status { get; set; } = String.Empty;
        public User user { get; set; } = new();
        public UserMacros userMacros { get; set; } = new();
        public CombineUser_UserMacros User_UserMacros { get; set; } = new();
        
        public void OnGet() { }
        public async Task<IActionResult> OnPostAddUser(CombineUser_UserMacros User_UserMacros)
        {

                var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
                var client = httpClient.CreateClient();
                client.BaseAddress = new Uri(config["BaseAddress"]);
                var jsoncategory = JsonConvert.SerializeObject(User_UserMacros);
                var content = new StringContent(jsoncategory, Encoding.UTF8, "application/json");
                var request = await client.PostAsync("/api/add-user", content);
            
            if (request.IsSuccessStatusCode)
            {
                string id = request.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                HttpContext.Session.SetString("Id", id);
                
                
                return RedirectToPage("/Main/Home");
                //return new NoContentResult();
            }
            Msg = "User Already Exists";
            Status = "error";
            RedirectToPage("");
            return Page();
        }
    }
}

BeFit_Website/BeFit_Website/Pages/UserInfo/EditUserData.cshtml
@page
@model BeFit_Website.Pages.UserInfo.EditUserModel
@{
    <link href="~/css/edituserdata.css" rel="stylesheet" />

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/photos/4.png" width="80" draggable="false" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-page="/Main/Home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"  data-toggle="dropdown" aria-expanded="false">Profile</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-page="/UserInfo/EditUserData">Edit Profile</a>

                        <a class="dropdown-item" asp-page="/Main/UserFeedbacks">feedback</a>
                        <a class="dropdown-item" asp-page="/UserInfo/Login">Log out</a>

                    </div>
                </li>
            </ul>

        </div>
    </nav>
    <main role="main">
  
        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
      
        </div>
  
        <div class="container">
            <!-- Example row of columns -->
            <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-4 order-md-2 mb-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted head">IMAGE</span>
                    </h4>

                        <ul class="list-group mb-3">
                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div class="col-md-4 profile-pic">
                                    @if (Model.user.ProfileUrl == null)
                                    {
                                        <img src="https://www.kindpng.com/picc/m/24-248394_user-icon-hd-png-download.png" id="output" width="200"
                                             style="width: 165px;height: 165px;box-shadow: 0 0 10px 0 rgba(255,255,255,.35);border-radius: 100px;z-index: 0;border: 2px solid gray;" />
                                    }else {
                                    <img src="@Model.user.ProfileUrl" id="output" width="200"
                                     style="width: 165px;height: 165px;box-shadow: 0 0 10px 0 rgba(255,255,255,.35);border-radius: 100px;z-index: 0; border: 2px solid gray;" />
                                    }
                            </div>
                        </ul>
                        <div class="modal-footer">
                            <label for="file-upload" class="btn btn-secondary" style="background:linear-gradient(to top, #1488cc, #2b32b2);">Change image</label>
                            <input type="file" id="file-upload" asp-for="user.ProfilePhoto" style="display:none;" data-dismiss="modal" onchange="loadFile(event)">
                            <!--<button id="SaveBtn" type="button" class="btn btn-primary">Save changes</button>-->
                        </div>

                </div>
                <div class="col-md-8 order-md-1">
                    <h4 class="mb-3 head">Edit Profile</h4>

                        <div class="mb-3">
                            <label for="username">User Name</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                </div>
                                <input type="text" class="BtnBtn" id="UserName" placeholder="User Name" asp-for="user.UserName" required>
                                <div class="invalid-feedback" style="width: 100%;">
                                Your User Name is required.
                                </div>
                            </div>
                            </div>
                        <div class="mb-3">
                        <label for="Email">Email</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                    <span class="input-group-text">&#64;</span>
                            </div>
                            <input type="email" class="BtnBtnV2" id="Email" placeholder="Email" asp-for="user.Email" required>
                            <div class="invalid-feedback" style="width: 100%;">
                            Your Email is required.
                            </div>
                        </div>
                        </div>
                        <div class="mb-3">
                            <label for="Password">Password</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                </div>
                                <input type="password" class="BtnBtn" id="Password" placeholder="Password" asp-for="user.Password" minlength="8" required>
                                <div class="invalid-feedback" style="width: 100%;">
                                Your Password is required.
                                </div>
                            </div>
                            </div>
                           <!-- <a href="UserMacros.html"><button id="SaveBtn" class="btn btn-primary btn-lg btn-block" asp-page="/UserInfo/EditUserMacros">Edit Your Macros</button></a> -->
                            <a class="btn btn-secondary" asp-page="/UserInfo/EditUserMacros">Edit Macros</a>
                        <button type="submit" asp-page-handler="EditUser" id="SaveBtn" class="btn btn-primary" style="background:linear-gradient(to top, #1488cc, #2b32b2);">Save</button>
                </div>
            </div>
            </form>
      
      
        </div>
  
      <hr>
  
  
  </main>
}
<script src="~/js/edituserdata.js"></script>

`@if (@Model.Msg != null)
{
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    if (@Model.Status == "error")
    {
        <script type="text/javascript">
            Swal.fire({
                icon: 'error',
                title: '@Model.Msg',
                showConfirmButton: true
            })
        </script>
    }
}
@section Scripts{
    @{
        <partial name="_NavBar" />
    }
}

BeFit_Website/BeFit_Website/Pages/UserInfo/EditUserMacros.cshtml
@page
@model BeFit_Website.Pages.UserInfo.EditUserMacrosModel
@{
    <link href="~/css/editusermacros.css" rel="stylesheet" />

    <main role="main">
        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">

        </div>
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-4 order-md-2 mb-4">

                    </div>
                    <div class="col-md-8 order-md-1">
                        <h4 class="mb-3 head">User Macros</h4>

                        <div class="mb-3">
                            <label for="Height">Height(cm)</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                </div>
                                @if (Model.userMacros.Age > 20 && Model.userMacros.Age < 60)
                                {
                                    <input type="number" asp-for="userMacros.Height" class="form-control" id="Height" placeholder="Height" readonly="true" required>
                                } else
                                {
                                    <input type="number" asp-for="userMacros.Height" class="form-control" id="Height" placeholder="Height" required>
                                }
                            </div>
                        <span asp-validation-for="userMacros.Height" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label for="Weight">Weight(kg)</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            </div>
                            <input type="number" asp-for="userMacros.Weight" class="form-control" id="Weight" placeholder="Weight" required>
                        </div>
                        <span asp-validation-for="userMacros.Weight" class="text-danger"></span>
                    </div>
                        <div class="mb-3">
                            <label for="Age">Date of Birth</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                </div>
                                <input type="Date" step="1" asp-for="userMacros.DateOfBirth" class="form-control" id="Age" readonly="true" required>
                            </div>
                            <span asp-validation-for="userMacros.Age" class="text-danger"></span>
                        </div>
                    <div class="mb-3">
                        <label for="Age">Age</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            </div>
                            <input type="number" step="1" asp-for="userMacros.Age" class="form-control" id="Age" placeholder="Age" readonly="true" required>
                        </div>
                        <span asp-validation-for="userMacros.Age" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label for="inputState">Gender</label>
                            <input asp-for="userMacros.Gender" id="inputState" class="form-control" readonly="true">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputState">Goal</label>
                            <select id="inputState" class="form-control" asp-for="userMacros.Goal" required>
                              <!--<option value="" hidden>Goal...</option>-->
                              <option value="Gain">Gain</option>
                              <option value="Lose">Lose</option>
                              <option value="Maintain">Maintain</option>
                            </select>
                        </div>

                        <div class="form-group col-md-4">
                            <label for="inputState">Activity level</label>
                            <select id="inputState" class="form-control" asp-for="userMacros.ActivityLevel" required>
                              <!--<option selected>Activity level...</option>-->
                              <option value="Sedentary">Sedentary (No Exercise)</option>
                              <option value="Lightly">Lightly Active (1 - 3 days)</option>
                              <option value="Moderately">Moderately Active (3 - 5 days)</option>
                              <option value="Very">Very Active (6 - 7 days)</option>
                              <option value="Extra">Extra Active (twice per day)</option>
                            </select>
                        </div>
                        @if (Model.userMacros.Disease == "None")
                        {
                            <div class="form-group col-md-4">
                                        <label for="inputState">Disease</label>
                                        <select id="inputState" class="form-control" asp-for="userMacros.Disease" required>
                                            <!--<option selected>Activity level...</option>-->
                                            <option value="" hidden>Disease...</option>
                                            <option value="None">None</option>
                                            <option value="Diabetes">Diabetes</option>
                                            <option value="Blood Pressure">Blood Pressure</option>
                                            <option value="Cholesterol">Cholesterol</option>
                                        </select>
                                </div>
                                
                            }
                            else
                            {
                            <div class="form-group col-md-4">
                                <label for="inputState">Disease</label>
                                <input asp-for="userMacros.Disease" id="inputState" class="form-control" readonly="true">
                            </div>
                            }
                        </div>
                    <div class="modal-footer">
                         <a asp-page="/UserInfo/EditUserData" class="btn btn-secondary" data-dismiss="modal">Back</a>
                            <button type="submit" id="SaveBtn" class="btn btn-primary" style="background:linear-gradient(to top, #1488cc, #2b32b2);">Save</button>
                    </div>

            </div>
        </div>
        </form>
      </div>
  
      <hr>
  
  </main>
}

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_NavBar" />
    }
}

BeFit_Website/BeFit_Website/Pages/UserInfo/SignUp.cshtml
@page
@model BeFit_Website.Pages.UserInfo.SignUpModel
@{
    <link href="~/css/register.css" rel="stylesheet" />
    <div class="container" id="container">
        <form method="post" enctype="multipart/form-data">
	        <div class="form-container sign-up-container">
                <div class="Sign-Up-form">

                        <input asp-for="User_UserMacros.CombinedUserMacros.Height" type="number" value="" class="mb-3 form-control" placeholder="Height(cm)"/>
                        <span asp-validation-for="User_UserMacros.CombinedUserMacros.Height" class="text-danger" style="color:#aa0909"></span>
			            
                        <input asp-for="User_UserMacros.CombinedUserMacros.Weight" value="" class="mb-3" placeholder="Weight(kg)" type="number" />
                        <span asp-validation-for="User_UserMacros.CombinedUserMacros.Weight" class="text-danger" style="color:#aa0909"></span>

                        <input type="date" asp-for="User_UserMacros.CombinedUserMacros.DateOfBirth" class="mb-4" value="Date of Birth">
                        <span asp-validation-for="User_UserMacros.CombinedUserMacros.DateOfBirth" class="text-danger" style="color:#aa0909"></span>

                    <div class="row mb-3">
                        <div class="form-group col-md-4">
                            <!-- <label for="inputState">Gender</label> -->
                                <select id="inputState" class="sign-up-select" asp-for="User_UserMacros.CombinedUserMacros.Gender">
                              <option value="" hidden>Gender...</option>
                              <option value="Male">Male</option>
                              <option value="Female">Female</option>
                            </select>
                        </div>
                            <span asp-validation-for="User_UserMacros.CombinedUserMacros.Gender" class="text-danger" style="color:#aa0909"></span>
                        <div class="form-group col-md-4">
                            <!-- <label for="inputState">Goal</label> -->
                                <select id="inputState" class="sign-up-select" asp-for="User_UserMacros.CombinedUserMacros.Goal">
                              <option value="" hidden>Goal...</option>
                              <option value="Gain">Gain</option>
                              <option value="Lose">Lose</option>
                              <option value="Maintain">Maintain</option>
                            </select>
                        </div>
                            <span asp-validation-for="User_UserMacros.CombinedUserMacros.Goal" class="text-danger" style="color:#aa0909"></span>

                        <div class="form-group col-md-4">
                            <!-- <label for="inputState">Activity level</label> -->
                                <select id="inputState" class="sign-up-select" asp-for="User_UserMacros.CombinedUserMacros.ActivityLevel">
                              <option value="" hidden>Activity level...</option>
                              <option value="Sedentary">Sedentary (No Exercise)</option>
                              <option value="Lightly">Lightly Active (1 - 3 days)</option>
                              <option value="Moderately">Moderately Active (3 - 5 days)</option>
                              <option value="Very">Very Active (6 - 7 days)</option>
                              <option value="Extra">Extra Active (twice per day)</option>
                            </select>
                        </div>
                            <span asp-validation-for="User_UserMacros.CombinedUserMacros.Disease" class="text-danger" style="color:#aa0909"></span>
                        <div class="form-group col-md-4">
                            <!-- <label for="inputState">Activity level</label> -->
                            <select id="inputState" class="sign-up-select" asp-for="User_UserMacros.CombinedUserMacros.Disease">
                                <option value="" hidden>Disease...</option>
                                <option value="None">None</option>
                                <option value="Diabetes">Diabetes</option>
                                <option value="Blood Pressure">Blood Pressure</option>
                                <option value="Cholesterol">Cholesterol</option>
                            </select>
                        </div>
                        <span asp-validation-for="User_UserMacros.CombinedUserMacros.Disease" class="text-danger" style="color:#aa0909"></span>
                    </div>

                    <button type="submit" class="signup-btn" asp-page-handler="AddUser">Sign Up</button>
                            
                </div>
       
	        </div>
	        <div class="form-container sign-in-container">
                <div class="Sign-Up-form">
			    <h1 class="Sign-Up-Header">Sign Up</h1>
                    <div class="social-container">
                        <img src="~/photos/be-fit16.png" width="80" draggable="false" />
		             </div>
                    <input asp-for="User_UserMacros.CombinedUser.UserName" type="text" placeholder="User Name" id="username"/>
                    <span asp-validation-for="User_UserMacros.CombinedUser.UserName" class="text-danger" style="color:#aa0909"></span>
                    <input asp-for="User_UserMacros.CombinedUser.Email" type="email"   placeholder="Email" id="email"/>
                    <span asp-validation-for="User_UserMacros.CombinedUser.Email" class="text-danger" style="color:#aa0909"></span>
                    <input asp-for="User_UserMacros.CombinedUser.Password" type="password" placeholder="Password" id="password" minlength="8" />
                    <span asp-validation-for="User_UserMacros.CombinedUser.Password" class="text-danger" style="color:#aa0909"></span>
                </div>
            </div>
            <div class="overlay-container">
		        <div class="overlay">
			        <div class="overlay-panel overlay-left">
				                <h1>Hello, Friend!</h1>
				                <p>To get your plan please continue with filling your macros</p>
				                <button type="button" class="ghost" id="signIn">Back</button>
			        </div>
			        <div class="overlay-panel overlay-right">
                        <h1>Hello, Friend!</h1>
				                <p>Enter your personal details and start journey with us</p>
                        <button type="button" class="ghost" style="display:none;" id="signUp">Next</button>
                            <!-- type="submit" asp-page-handler="AddUser" -->
			        </div>
		        </div>
	        </div>
        </form>
    </div>
}
<script src="~/js/bootstrap.bundle.min.js"></script>
<script src="~/js/bootstrap.js"></script>
<script src="~/js/register.js"></script>
    


  <script>
//   $('#exampleModal').modal('show');
$('#exampleModal').modal({
  keyboard: false
})
  </script>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}
`@if (@Model.Msg != null)
{
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    if (@Model.Status == "error")
    {
        <script type="text/javascript">
            Swal.fire({
                icon: 'error',
                title: '@Model.Msg',
                showConfirmButton: true
            })
        </script>
    }
}