BeFit_Website/BeFit_Website/Pages/Main/Home.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text;

namespace BeFit_Website.Pages.Main
{
    public class HomeModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();

        public UserMacros userMacros { get; set; } = new();
        public List<SelectedFood> selectedFoodList { get; set; } = new();
        public UserMacrosDTO userMacrosDTO { get; set; } = new();
        public async Task OnGet()
        {
            // call user macros
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("api/get-user-macros/" + currentUser.ToString().Replace("\"", ""));

            if (request.IsSuccessStatusCode)
            {
                var stringData = request.Content.ReadAsStringAsync().Result;
                userMacros = JsonConvert.DeserializeObject<UserMacros>(stringData);
                request = await client.GetAsync("api/get-user-calories/" + currentUser.ToString().Replace("\"", ""));
                if (request.IsSuccessStatusCode)
                {
                    var stringData2 = request.Content.ReadAsStringAsync().Result;
                    userMacrosDTO = JsonConvert.DeserializeObject<UserMacrosDTO>(stringData2);
                    request = await client.GetAsync("api/get-selected-food/" + currentUser.ToString().Replace("\"", ""));
                    if (request.IsSuccessStatusCode)
                    {
                        var stringData3 = request.Content.ReadAsStringAsync().Result;
                        selectedFoodList = JsonConvert.DeserializeObject<List<SelectedFood>>(stringData3);
                    }
                }
            }
        }
        public async Task<IActionResult> OnPostDeleteSelectedFood(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/delete-selected-food/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }


    }
}

BeFit_Website/BeFit_Website/Pages/Main/UserFeedbacks.cshtml.cs
using BeFit_Website.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text;

namespace BeFit_Website.Pages.Main
{
    public class UserFeedbacksModel : PageModel
    {
        IConfiguration config = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json")
           .AddEnvironmentVariables()
           .Build();
        public List<GetFeedback> feedbackList { get; set; } = new();
        public Feedback Feedback { get; set; } = new();
        public User user { get; set; } = new();
        public async Task OnGet()
        {
            var currentUser = HttpContext.Session.GetString("Id");
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetStringAsync("api/get-feedbacks-for-user");

            if (request != null)
            {
                //var stringData = request.Content.ReadAsStringAsync().Result();
                feedbackList = JsonConvert.DeserializeObject<List<GetFeedback>>(request);
            }
            var request2 = await client.GetAsync("api/get-user-data/" + currentUser.ToString().Replace("\"", ""));

            if (request2.IsSuccessStatusCode)
            {
                var stringData = request2.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<User>(stringData);
            }
            
        }

        public async Task<IActionResult> OnPostAddFeedback(Feedback feedback)
        {
            var currentUser = HttpContext.Session.GetString("Id");
            feedback.UserId = Guid.Parse(currentUser.ToString().Replace("\"", ""));
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var jsoncategory = JsonConvert.SerializeObject(feedback);
            var content = new StringContent(jsoncategory, Encoding.UTF8, "application/json");
            var request = await client.PostAsync("/api/add-feedback", content);
            if (request.IsSuccessStatusCode)
            {

                return RedirectToPage("");
            }
            return new NoContentResult();
        }
        public async Task<IActionResult> OnPostDeleteFeedback(Guid itemid)
        {
            var httpClient = HttpContext.RequestServices.GetService<IHttpClientFactory>();
            var client = httpClient.CreateClient();
            client.BaseAddress = new Uri(config["BaseAddress"]);
            var request = await client.GetAsync("/api/delete-feedback/" + itemid);
            if (request.IsSuccessStatusCode)
            {
                return RedirectToPage("");
            }
            return new NoContentResult();
        }
    }
}

BeFit_Website/BeFit_Website/Pages/Main/Home.cshtml
@page
@model BeFit_Website.Pages.Main.HomeModel
@{
    // Retrieve data from the database
    double usedCalories = Math.Ceiling(Model.userMacros.DailyCalories - Model.userMacrosDTO.RemainingDailyCalories);
    double totalCalories = Model.userMacros.DailyCalories;
    double usedCarbs = Math.Ceiling(Model.userMacros.DailyCarbs - Model.userMacrosDTO.RemainingDailyCarbs);
    double totalCarbs = Model.userMacros.DailyCarbs;
    double usedFats = Math.Ceiling(Model.userMacros.DailyFats - Model.userMacrosDTO.RemainingDailyFats);
    double totalFats = Model.userMacros.DailyFats;
    double usedProtein = Math.Ceiling(Model.userMacros.DailyProtein - Model.userMacrosDTO.RemainingDailyProtein);
    double totalProtein = Model.userMacros.DailyProtein;

    // Calculate the completion percentage
    int usedCaloriesPercentage = (int)((double)usedCalories / totalCalories * 100);
    int usedCarbsPercentage = (int)((double)usedCarbs / totalCarbs * 100);
    int usedFatsPercentage = (int)((double)usedFats / totalFats * 100);
    int usedProteinPercentage = (int)((double)usedProtein / totalProtein * 100);

    // Set the style attribute of the progress bar
    string progressCaloriesStyle = $"width: {usedCaloriesPercentage}%";
    string progressCarbsStyle = $"width: {usedCarbsPercentage}%";
    string progressFatsStyle = $"width: {usedFatsPercentage}%";
    string progressProteinStyle = $"width: {usedProteinPercentage}%";
    }
@{

    <link href="~/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/css/home.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <a class="navbar-brand" asp-area="" asp-page="/Main/Home"><img src="~/photos/be-fit12.png" width="80" draggable="false" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-page="/Main/Home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-page="/FoodInfo/SearchForFood">Food <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-page="/Exercises/ShowExercises">Exercises <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-page="/Main/UserFeedbacks">Feedbacks <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Profile</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-page="/UserInfo/EditUserData">Edit Profile</a>
                        <a class="dropdown-item" asp-page="/UserInfo/Login">Log out</a>

                    </div>
                </li>
            </ul>

        </div>
    </nav>
    <div style="margin-top:150px;"></div>
    <div class="calorieContainer">
        <span class="calorieName">Calories [Total:@Model.userMacros.DailyCalories kcl]:</span>
        <span class="calorieInfo">Remaining: @Model.userMacrosDTO.RemainingDailyCalories</span>
        <div class="progress caloriesBarContainer">
            <div class="progress-bar bg-success remaining" role="progressbar" style="@progressCaloriesStyle" aria-valuenow="@usedCaloriesPercentage" aria-valuemin="0" aria-valuemax="100">@usedCalories</div>
        </div>
    </div>
    <div class="otherBarsContainer">
        <div class="carbContainer">
            <span class="barName">Carbs [Total:@Model.userMacros.DailyCarbs g]:</span>
            <span class="barInfo">Remaining: @Model.userMacrosDTO.RemainingDailyCarbs</span>
            <div class="progress">
                <div class="progress-bar bg-info" role="progressbar" style="@progressCarbsStyle" aria-valuenow="@usedCarbsPercentage" aria-valuemin="0" aria-valuemax="100">@usedCarbs</div>
            </div>
        </div>
        <div class="carbContainer">
            <span class="barName">Fats [Total:@Model.userMacros.DailyFats g]:</span>
            <span class="barInfo">Remaining: @Model.userMacrosDTO.RemainingDailyFats</span>
            <div class="progress">
                <div class="progress-bar bg-warning" role="progressbar" style="@progressFatsStyle" aria-valuenow="@usedFatsPercentage" aria-valuemin="0" aria-valuemax="100">@usedFats</div>
            </div>
        </div>
        <div class="carbContainer">
            <span class="barName">Protein [Total:@Model.userMacros.DailyProtein g]:</span>
            <span class="barInfo">Remaining: @Model.userMacrosDTO.RemainingDailyProtein</span>
            <div class="progress">
                <div class="progress-bar bg-danger" role="progressbar" style="@progressProteinStyle" aria-valuenow="@usedProteinPercentage" aria-valuemin="0" aria-valuemax="100">@usedProtein</div>
            </div>
        </div>
    </div>
    <a asp-page="/FoodInfo/SearchForFood"><button class="btn btn-primary" style="margin-left:45%;background: linear-gradient(to top, #1488cc, #2b32b2);"><i class="fas fa-plus"></i>Add Food</button></a>
    <div class="card-deck">
            <div class="card custom-card">
                <div class="card-header header">
                    <h5 class="card-title">Breakfast</h5>
                </div>
                <div class="card-body">
                @foreach (var obj in Model.selectedFoodList)
                {
                    if (obj.Meal == "Breakfast")
                    {
                        <ul class="list-group list-group-flush text-left">
                            <li class="list-group-item small">
                                @obj.FoodName
                                <span class="calories-count calories">@obj.Calories kcl</span>
                                <form method="post">
                                    <button class="btn btn-link delete-item" type="submit" asp-page-handler="DeleteSelectedFood" asp-route-itemid=@obj.Id><i class="fas fa-trash-alt"></i></button>
                                </form>
                                <br>
                                <span>@obj.Quantity</span>
                            </li>
                        </ul>
                    }
                }
                </div>
            </div>
                <div class="card custom-card">
                    <div class="card-header header">
                        <h5 class="card-title">Lunch</h5>
                    </div>
                    <div class="card-body">
                        @foreach (var obj in Model.selectedFoodList)
                        {
                            if (obj.Meal == "Lunch")
                            {
                                <ul class="list-group list-group-flush text-left">
                                    <li class="list-group-item small">
                                        @obj.FoodName
                                <span class="calories-count calories">@obj.Calories kcl</span>
                                        <form method="post">
                                            <button class="btn btn-link delete-item" type="submit" asp-page-handler="DeleteSelectedFood" asp-route-itemid=@obj.Id><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                        <br>
                                        <span>@obj.Quantity</span>
                                    </li>
                                </ul>
                            }
                        }
                    </div>
                </div>
                <div class="card custom-card">
                    <div class="card-header header">
                        <h5 class="card-title">Dinner</h5>
                    </div>
                    <div class="card-body">
                        @foreach (var obj in Model.selectedFoodList)
                        {
                            if (obj.Meal == "Dinner")
                            {
                                <ul class="list-group list-group-flush text-left">
                                    <li class="list-group-item small">
                                        @obj.FoodName
                                <span class="calories-count calories">@obj.Calories kcl</span>
                                        <form method="post">
                                            <button class="btn btn-link delete-item" type="submit" asp-page-handler="DeleteSelectedFood" asp-route-itemid=@obj.Id><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                        <br>
                                        <span>@obj.Quantity</span>
                                    </li>
                                </ul>
                            }
                        }
                    </div>
                </div>
                <div class="card custom-card">
                    <div class="card-header header">
                        <h5 class="card-title">Snacks</h5>
                    </div>
                    <div class="card-body">
                        @foreach (var obj in Model.selectedFoodList)
                        {
                            if (obj.Meal == "Snacks")
                            {
                                <ul class="list-group list-group-flush text-left">
                                    <li class="list-group-item small">
                                        @obj.FoodName
                                        <span class="calories-count calories">@obj.Calories kcl</span>
                                        <form method="post">
                                            <button class="btn btn-link delete-item" type="submit" asp-page-handler="DeleteSelectedFood" asp-route-itemid=@obj.Id><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                        <br>
                                        <span>@obj.Quantity</span>
                                    </li>
                                </ul>
                            }
                        }
                    </div>
                </div>
    </div>
}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="~/js/bootstrap.bundle.min.js"></script>

BeFit_Website/BeFit_Website/Pages/Main/UserFeedbacks.cshtml
@page
@model BeFit_Website.Pages.Main.UserFeedbacksModel
@{
    <link href="~/css/userfeedbacks.css" rel="stylesheet" />
    
    <div class="feedback-container">
        <div class="feedback-wrapper">
            <section class="feedback-post" style="margin-top:100px;">
                <header class="head">Add your Feedback</header>
                <form method="post" class="feedback-form" id="feedback-form" enctype="multipart/form-data">
                    <div class="feedback-content">
                        <img src="@Model.user.ProfileUrl" style="border-radius: 50%">
                        <div class="feedback-details">
                            <p>@Model.user.UserName</p>
                            <p id="datetime"></p>
                        </div>
                    </div>
                    <input id="yourInputFieldId" asp-for="Feedback.Message" placeholder="your feedback is important to us 💖" value="" required>
                    <button type="submit" asp-page-handler="AddFeedback" id="post-button" class="Post-button">Post</button>
                </form>
        </div>
    </div>
    @foreach (var obj in Model.feedbackList)
    {
        <div class="feedback-container">
            @{
                if (obj.UserId.ToString() == HttpContext.Session.GetString("Id").Replace("\"", ""))
                {
                    <form method="post" class="feedback-form" enctype="multipart/form-data">
                        <button class="delete" type="submit" asp-page-handler="DeleteFeedback" asp-route-itemid=@obj.Id>✖️</button>
                    </form>
                }
            }
            <div class="feedback-wrapper">
                <section class="feedback-post">
                    <form class="feedback-form">
                        <div class="feedback-content">
                            <img src="@obj.FeedbackUser.ProfileUrl" style="border-radius: 50%">
                            <div class="feedback-details">
                                <p>@obj.FeedbackUser.UserName</p>
                                <p>@obj.TimeCreated</p>
                            </div>
                        </div>
                        <input type="text" asp-for="@obj.Message" readonly="true">
                    </form>
            </div>
        </div>
                  }

}
<script src="~/js/userfeedbacks.js"></script>
@section Scripts{
    @{
        <partial name="_NavBar" />
    }
}